{
 "title": "App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Sus Txn Call",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (component) (sus_transactions_total{job=\"fastapi-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Sus Txn Call [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (component,category) (\n  rate(sus_transactions_total{}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Lowly Sus Txn Call [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (component,category) (\n  rate(sus_transactions_total{category=\"low\",job=\"fastapi-app\",instance=\"fastapi-app:8000\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Lowly Sus Txn Call [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (component,category) (\n  rate(sus_transactions_total{category=\"low\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "upstream_call_latency{}", "legendFormat": "{{component}}" }
   ]
  }
 ]
}